import { DatabaseSync } from 'node:sqlite';
import { mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { randomUUID } from 'node:crypto';
import type { Attachment, Comment, Project, Relation, Session, Task, TaskDetail, TaskInput, TaskPatch } from '../../packages/contracts/index.ts';
import { fail, validateTask } from './validation.ts';
import { migrate } from './storage/schema.ts';
import { activity, attachment, comment, iso, json, project, relation, Row, task } from './storage/serialization.ts';

type Actor = string;

export class Storage {
  readonly db: DatabaseSync;
  readonly subscribers = new Set<(revision: number) => void>();
  readonly closers = new Set<() => void>();
  private closed = false;

  constructor(dataDir: string) {
    if (dataDir !== ':memory:') mkdirSync(dataDir, { recursive: true });
    this.db = new DatabaseSync(dataDir === ':memory:' ? ':memory:' : join(dataDir, 'taskmanager.sqlite'));
    this.db.exec('PRAGMA foreign_keys = ON; PRAGMA journal_mode = WAL; PRAGMA busy_timeout = 5000;');
    migrate(this.db);
    if (this.listProjects().length === 0) this.write(() => this.createProject({ name: '本地项目', prefix: 'LOCAL', workspacePath: null, labels: [], readme: '' }));
  }

  revision() { return Number((this.db.prepare("SELECT value FROM meta WHERE key = 'revision'").get() as Row).value); }
  write<T>(operation: () => T): T {
    this.db.exec('BEGIN IMMEDIATE');
    let result: T;
    try { result = operation(); this.db.exec("UPDATE meta SET value = value + 1 WHERE key = 'revision'; COMMIT"); }
    catch (error) { try { this.db.exec('ROLLBACK'); } catch { /* Preserve the original error. */ } throw error; }
    const revision = this.revision();
    for (const subscriber of this.subscribers) { try { subscriber(revision); } catch { /* Notification cannot undo a commit. */ } }
    return result;
  }

  listProjects() { return this.db.prepare(`SELECT p.*, COUNT(t.id) AS task_count FROM projects p LEFT JOIN tasks t ON t.project_id = p.id AND t.archived_at IS NULL GROUP BY p.id ORDER BY p.created_at, p.id`).all().map((row) => project(row as Row)); }
  createProject(input: { name: string; prefix?: string; workspacePath?: string | null; labels?: string[]; readme?: string }): Project {
    const now = iso(); const prefix = (input.prefix ?? (input.name.replace(/[^a-z0-9]/gi, '').slice(0, 6) || 'TASK')).toUpperCase(); const project = { id: randomUUID(), name: input.name.trim(), prefix, workspacePath: input.workspacePath ?? null, labels: input.labels ?? [], readme: input.readme ?? '', version: 1, createdAt: now, updatedAt: now, taskCount: 0 } satisfies Project;
    try { this.db.prepare('INSERT INTO projects(id,name,prefix,workspace_path,labels,readme,version,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?)').run(project.id, project.name, project.prefix, project.workspacePath, json(project.labels), project.readme, project.version, project.createdAt, project.updatedAt); }
    catch (error) { if (String(error).includes('UNIQUE')) fail(409, 'PROJECT_PREFIX_EXISTS', 'Project prefix already exists'); throw error; }
    return project;
  }
  getProject(id: string) { const row = this.db.prepare(`SELECT p.*, COUNT(t.id) AS task_count FROM projects p LEFT JOIN tasks t ON t.project_id = p.id AND t.archived_at IS NULL WHERE p.id = ? GROUP BY p.id`).get(id) as Row | undefined; if (!row) fail(404, 'PROJECT_NOT_FOUND', 'Project not found'); return project(row); }
  updateProject(id: string, input: { version: number; name?: string; workspacePath?: string | null; labels?: string[]; readme?: string }) {
    const current = this.getProject(id); if (current.version !== input.version) fail(409, 'VERSION_CONFLICT', `Project changed; current version is ${current.version}`); const next = { ...current, ...input, version: current.version + 1, updatedAt: iso() };
    this.db.prepare('UPDATE projects SET name=?,workspace_path=?,labels=?,readme=?,version=?,updated_at=? WHERE id=? AND version=?').run(next.name, next.workspacePath, json(next.labels), next.readme, next.version, next.updatedAt, id, current.version); return this.getProject(id);
  }
  deleteProject(id: string, version: number) { const project = this.getProject(id); if (project.version !== version) fail(409, 'VERSION_CONFLICT', `Project changed; current version is ${project.version}`); const count = Number((this.db.prepare('SELECT COUNT(*) AS count FROM tasks WHERE project_id = ?').get(id) as Row).count); if (count > 0) fail(409, 'PROJECT_NOT_EMPTY', 'Project still contains tasks'); this.db.prepare('DELETE FROM projects WHERE id = ?').run(id); }

  listTasks(filters: { projectId?: string; status?: string; search?: string; archived?: string }) {
    const clauses = ['1 = 1']; const values: (string | number)[] = [];
    if (filters.projectId) { clauses.push('t.project_id = ?'); values.push(filters.projectId); }
    if (filters.status) { clauses.push('t.status = ?'); values.push(filters.status); }
    if (filters.archived !== 'all') clauses.push(filters.archived === 'true' ? 't.archived_at IS NOT NULL' : 't.archived_at IS NULL');
    if (filters.search?.trim()) { clauses.push('(t.identifier LIKE ? OR t.title LIKE ? OR t.description LIKE ? OR t.labels LIKE ?)'); const search = `%${filters.search.trim()}%`; values.push(search, search, search, search); }
    return this.db.prepare(`SELECT * FROM tasks t WHERE ${clauses.join(' AND ')} ORDER BY t.status, t.sort_order, t.created_at, t.id`).all(...values).map((row) => task(this.db, row as Row));
  }
  getTask(id: string) { const row = this.db.prepare('SELECT * FROM tasks WHERE id = ? OR identifier = ?').get(id, id) as Row | undefined; if (!row) fail(404, 'TASK_NOT_FOUND', 'Task not found'); return task(this.db, row); }
  private nextSort(projectId: string, status: string) { return Number((this.db.prepare('SELECT COALESCE(MAX(sort_order), -1) + 1 AS next FROM tasks WHERE project_id = ? AND status = ? AND archived_at IS NULL').get(projectId, status) as Row).next); }
  private nextIdentifier(projectId: string) { return String((this.db.prepare('INSERT INTO project_counters(project_id,value) VALUES (?,1) ON CONFLICT(project_id) DO UPDATE SET value=value+1 RETURNING value').get(projectId) as Row).value); }
  createTask(input: TaskInput, actor: Actor) {
    const project = this.getProject(input.projectId); const now = iso(); const task: Task = { id: randomUUID(), identifier: `${project.prefix}-${this.nextIdentifier(project.id)}`, projectId: project.id, title: input.title.trim(), description: input.description ?? '', status: input.status ?? 'todo', priority: input.priority ?? 'none', labels: input.labels ?? [], assignee: input.assignee ?? '', creator: actor, sortOrder: input.sortOrder ?? this.nextSort(project.id, input.status ?? 'todo'), startDate: input.startDate ?? null, dueDate: input.dueDate ?? null, recurrence: input.recurrence ?? null, developmentContext: input.developmentContext ?? null, archivedAt: input.archivedAt ?? null, version: 1, createdAt: now, updatedAt: now, sessions: [] };
    validateTask(task); this.db.prepare('INSERT INTO tasks(id,identifier,project_id,title,description,status,priority,labels,assignee,creator,sort_order,start_date,due_date,recurrence,development_context,archived_at,version,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(task.id, task.identifier, task.projectId, task.title, task.description, task.status, task.priority, json(task.labels), task.assignee, task.creator, task.sortOrder, task.startDate, task.dueDate, task.recurrence ? json(task.recurrence) : null, task.developmentContext ? json(task.developmentContext) : null, task.archivedAt, task.version, task.createdAt, task.updatedAt); this.addActivity(task.id, actor, 'task.created', {}, { status: task.status, title: task.title }); return this.getTask(task.id);
  }
  updateTask(id: string, input: TaskPatch, actor: Actor) {
    const current = this.getTask(id); if (current.version !== input.version) fail(409, 'VERSION_CONFLICT', `Task changed; current version is ${current.version}`); const next = { ...current, ...input, id: current.id, identifier: current.identifier, projectId: input.projectId ?? current.projectId, version: current.version + 1, updatedAt: iso(), sessions: current.sessions } as Task;
    if (next.projectId !== current.projectId) { this.getProject(next.projectId); if (this.db.prepare('SELECT 1 FROM relations WHERE source_id = ? OR target_id = ? LIMIT 1').get(current.id, current.id)) fail(409, 'TASK_HAS_RELATIONS', 'Move the task relations before changing project'); }
    validateTask(next); this.db.prepare('UPDATE tasks SET project_id=?,title=?,description=?,status=?,priority=?,labels=?,assignee=?,sort_order=?,start_date=?,due_date=?,recurrence=?,development_context=?,archived_at=?,version=?,updated_at=? WHERE id=? AND version=?').run(next.projectId, next.title.trim(), next.description, next.status, next.priority, json(next.labels), next.assignee, next.sortOrder, next.startDate, next.dueDate, next.recurrence ? json(next.recurrence) : null, next.developmentContext ? json(next.developmentContext) : null, next.archivedAt, next.version, next.updatedAt, current.id, current.version); this.addActivity(current.id, actor, 'task.updated', { status: current.status, priority: current.priority, title: current.title, projectId: current.projectId, archivedAt: current.archivedAt, sortOrder: current.sortOrder }, { status: next.status, priority: next.priority, title: next.title, projectId: next.projectId, archivedAt: next.archivedAt, sortOrder: next.sortOrder }); return this.getTask(current.id);
  }
  deleteTask(id: string, version: number) { const current = this.getTask(id); if (current.version !== version) fail(409, 'VERSION_CONFLICT', `Task changed; current version is ${current.version}`); if (!current.archivedAt) fail(409, 'TASK_NOT_ARCHIVED', 'Archive the task before deleting it'); this.db.prepare('DELETE FROM tasks WHERE id = ?').run(current.id); }

  listComments(taskId: string) { this.getTask(taskId); return this.db.prepare('SELECT * FROM comments WHERE task_id = ? ORDER BY created_at, id').all(taskId).map((row) => comment(row as Row)); }
  createComment(taskId: string, body: string, actor: Actor) { const task = this.getTask(taskId); if (task.archivedAt) fail(409, 'TASK_ARCHIVED', 'Archived tasks cannot receive comments'); const now = iso(); const comment: Comment = { id: randomUUID(), taskId: task.id, body, author: actor, version: 1, createdAt: now, updatedAt: now }; this.db.prepare('INSERT INTO comments(id,task_id,body,author,version,created_at,updated_at) VALUES (?,?,?,?,?,?,?)').run(comment.id, comment.taskId, comment.body, comment.author, comment.version, comment.createdAt, comment.updatedAt); this.addActivity(task.id, actor, 'comment.created', {}, { commentId: comment.id }); return comment; }
  updateComment(id: string, body: string, version: number, actor: Actor) { const row = this.db.prepare('SELECT * FROM comments WHERE id = ?').get(id) as Row | undefined; if (!row) fail(404, 'COMMENT_NOT_FOUND', 'Comment not found'); const current = comment(row); if (current.version !== version) fail(409, 'VERSION_CONFLICT', `Comment changed; current version is ${current.version}`); const next = { ...current, body, version: current.version + 1, updatedAt: iso() }; this.db.prepare('UPDATE comments SET body=?,version=?,updated_at=? WHERE id=? AND version=?').run(next.body, next.version, next.updatedAt, id, version); this.addActivity(current.taskId, actor, 'comment.updated', { body: current.body }, { body: next.body }); return next; }
  deleteComment(id: string, version: number, actor: Actor) { const row = this.db.prepare('SELECT * FROM comments WHERE id = ?').get(id) as Row | undefined; if (!row) fail(404, 'COMMENT_NOT_FOUND', 'Comment not found'); const current = comment(row); if (current.version !== version) fail(409, 'VERSION_CONFLICT', `Comment changed; current version is ${current.version}`); this.db.prepare('DELETE FROM comments WHERE id = ?').run(id); this.addActivity(current.taskId, actor, 'comment.deleted', { commentId: id }, {}); }
  listActivities(taskId: string) { this.getTask(taskId); return this.db.prepare('SELECT * FROM activities WHERE task_id = ? ORDER BY created_at, id').all(taskId).map((row) => activity(row as Row)); }
  listAttachments(taskId: string) { this.getTask(taskId); return this.db.prepare('SELECT id,task_id,comment_id,filename,content_type,size,created_at FROM attachments WHERE task_id = ? ORDER BY created_at, id').all(taskId).map((row) => attachment(row as Row)); }
  getAttachment(id: string) { const row = this.db.prepare('SELECT * FROM attachments WHERE id = ?').get(id) as Row | undefined; if (!row) fail(404, 'ATTACHMENT_NOT_FOUND', 'Attachment not found'); return { attachment: attachment(row), content: row.content as Uint8Array }; }
  createAttachment(taskId: string, input: { filename: string; contentType: string; content: Uint8Array }, actor: Actor, commentId?: string) { const task = this.getTask(taskId); if (commentId && !this.db.prepare('SELECT 1 FROM comments WHERE id = ? AND task_id = ?').get(commentId, task.id)) fail(404, 'COMMENT_NOT_FOUND', 'Comment not found'); const id = randomUUID(); const createdAt = iso(); const attachment: Attachment = { id, taskId: task.id, commentId: commentId ?? null, filename: input.filename, contentType: input.contentType, size: input.content.byteLength, createdAt }; this.db.prepare('INSERT INTO attachments(id,task_id,comment_id,filename,content_type,size,content,created_at) VALUES (?,?,?,?,?,?,?,?)').run(id, task.id, commentId ?? null, input.filename, input.contentType, input.content.byteLength, input.content, createdAt); this.addActivity(task.id, actor, 'attachment.created', {}, { attachmentId: id }); return attachment; }
  deleteAttachment(id: string, actor: Actor) { const { attachment } = this.getAttachment(id); this.db.prepare('DELETE FROM attachments WHERE id = ?').run(id); this.addActivity(attachment.taskId, actor, 'attachment.deleted', { attachmentId: id }, {}); }

  listRelations(taskId: string) { this.getTask(taskId); return this.db.prepare('SELECT * FROM relations WHERE source_id = ? OR target_id = ? ORDER BY created_at, id').all(taskId, taskId).map((row) => relation(row as Row)); }
  addRelation(taskId: string, targetId: string, type: Relation['type'], version: number, actor: Actor) { const task = this.getTask(taskId); const target = this.getTask(targetId); if (task.version !== version) fail(409, 'VERSION_CONFLICT', `Task changed; current version is ${task.version}`); if (task.projectId !== target.projectId) fail(422, 'CROSS_PROJECT_RELATION', 'Relations must stay within one project'); let sourceId = task.id; let destinationId = target.id; if (type === 'related' && sourceId > destinationId) [sourceId, destinationId] = [destinationId, sourceId]; if (type === 'parent') { if (this.db.prepare("SELECT 1 FROM relations WHERE type='parent' AND target_id=?").get(destinationId)) fail(409, 'PARENT_EXISTS', 'A task can only have one parent'); if (this.parentReachable(destinationId, sourceId)) fail(409, 'RELATION_CYCLE', 'Parent relation would create a cycle'); } const relation: Relation = { id: randomUUID(), sourceId, targetId: destinationId, type }; try { this.db.prepare('INSERT INTO relations(id,type,source_id,target_id,created_at) VALUES (?,?,?,?,?)').run(relation.id, relation.type, relation.sourceId, relation.targetId, iso()); } catch (error) { if (String(error).includes('UNIQUE')) fail(409, 'RELATION_EXISTS', 'Relation already exists'); throw error; } this.touchTask(task.id); if (target.id !== task.id) this.touchTask(target.id); this.addActivity(task.id, actor, 'relation.created', {}, relation as unknown as Record<string, unknown>); return relation; }
  removeRelation(id: string, taskId: string, version: number, actor: Actor) { const row = this.db.prepare('SELECT * FROM relations WHERE id = ?').get(id) as Row | undefined; if (!row) fail(404, 'RELATION_NOT_FOUND', 'Relation not found'); const currentRelation = relation(row); const task = this.getTask(taskId); if (task.version !== version) fail(409, 'VERSION_CONFLICT', `Task changed; current version is ${task.version}`); if (currentRelation.sourceId !== task.id && currentRelation.targetId !== task.id) fail(403, 'RELATION_OWNER_MISMATCH', 'Relation does not belong to this task'); this.db.prepare('DELETE FROM relations WHERE id = ?').run(id); this.touchTask(currentRelation.sourceId); if (currentRelation.targetId !== currentRelation.sourceId) this.touchTask(currentRelation.targetId); this.addActivity(task.id, actor, 'relation.deleted', currentRelation as unknown as Record<string, unknown>, {}); }
  private parentReachable(from: string, wanted: string) { const rows = this.db.prepare("WITH RECURSIVE descendants(id) AS (SELECT target_id FROM relations WHERE type='parent' AND source_id=? UNION ALL SELECT r.target_id FROM relations r JOIN descendants d ON r.source_id=d.id WHERE r.type='parent') SELECT id FROM descendants").all(from); return rows.some((row) => String((row as Row).id) === wanted); }
  addSession(taskId: string, input: Omit<Session, 'id'>, version: number, actor: Actor) { const task = this.getTask(taskId); if (task.version !== version) fail(409, 'VERSION_CONFLICT', `Task changed; current version is ${task.version}`); try { this.db.prepare('INSERT INTO sessions(id,task_id,platform,session_id,project_id,host_id,workspace_path,project_kind,created_at) VALUES (?,?,?,?,?,?,?,?,?)').run(randomUUID(), task.id, input.platform, input.sessionId, input.projectId ?? null, input.hostId ?? null, input.workspacePath ?? null, input.projectKind ?? null, iso()); } catch (error) { if (String(error).includes('UNIQUE')) fail(409, 'SESSION_EXISTS', 'Session is already linked'); throw error; } this.touchTask(task.id); this.addActivity(task.id, actor, 'session.created', {}, { platform: input.platform, sessionId: input.sessionId }); return this.getTask(task.id); }
  removeSession(taskId: string, sessionId: string, version: number, actor: Actor) { const task = this.getTask(taskId); if (task.version !== version) fail(409, 'VERSION_CONFLICT', `Task changed; current version is ${task.version}`); const result = this.db.prepare('DELETE FROM sessions WHERE task_id=? AND session_id=?').run(taskId, sessionId); if (Number(result.changes) === 0) fail(404, 'SESSION_NOT_FOUND', 'Session not found'); this.touchTask(taskId); this.addActivity(taskId, actor, 'session.deleted', { sessionId }, {}); return this.getTask(taskId); }
  detail(id: string): TaskDetail { const task = this.getTask(id); return { task, comments: this.listComments(task.id), activities: this.listActivities(task.id), attachments: this.listAttachments(task.id), relations: this.listRelations(task.id) }; }
  private touchTask(id: string) { this.db.prepare('UPDATE tasks SET version=version+1,updated_at=? WHERE id=?').run(iso(), id); }
  private addActivity(taskId: string, actor: Actor, action: string, before: Record<string, unknown>, after: Record<string, unknown>) { const changes: Record<string, { before: unknown; after: unknown }> = {}; for (const key of new Set([...Object.keys(before), ...Object.keys(after)])) if (JSON.stringify(before[key]) !== JSON.stringify(after[key])) changes[key] = { before: before[key] ?? null, after: after[key] ?? null }; this.db.prepare('INSERT INTO activities(id,task_id,actor,action,changes,created_at) VALUES (?,?,?,?,?,?)').run(randomUUID(), taskId, actor, action, json(changes), iso()); }
  close() { if (this.closed) return; this.closed = true; for (const close of this.closers) close(); this.closers.clear(); this.subscribers.clear(); this.db.close(); }
}
