import { useState, type FormEvent } from 'react';
import { ErrorMessage, Modal } from './shared';
import { useLocale } from '../lib/locale';

export function ProjectModal({ onClose, onCreated }: { onClose: () => void; onCreated: (input: { name: string; prefix?: string; workspacePath?: string | null }) => Promise<void> }) {
  const { text } = useLocale();
  const [name, setName] = useState(''); const [prefix, setPrefix] = useState(''); const [workspacePath, setWorkspacePath] = useState(''); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); if (!name.trim()) { setError(text('请输入项目名称', 'Enter a project name')); return; } setSaving(true); try { await onCreated({ name: name.trim(), prefix: prefix.trim() || undefined, workspacePath: workspacePath.trim() || null }); } catch (err) { setError(err instanceof Error ? err.message : String(err)); } finally { setSaving(false); } }
  return <Modal title={text('新建项目', 'New project')} onClose={onClose}><form className="form-stack" onSubmit={(event) => void submit(event)}><label>{text('项目名称', 'Project name')}<input autoFocus value={name} onChange={(event) => setName(event.target.value)} placeholder="例如：TaskManager" /></label><label>{text('编号前缀', 'Identifier prefix')}<span className="field-hint">{text('可选，最多 12 个字符', 'Optional, up to 12 characters')}</span><input value={prefix} onChange={(event) => setPrefix(event.target.value.toUpperCase())} placeholder="例如：TM" maxLength={12} /></label><label>{text('工作区路径', 'Workspace path')}<span className="field-hint">{text('可选，用于关联本地代码目录', 'Optional, links a local code directory')}</span><input value={workspacePath} onChange={(event) => setWorkspacePath(event.target.value)} placeholder="/Users/you/project" /></label><ErrorMessage error={error} /><div className="form-actions"><button type="button" className="button secondary" onClick={onClose}>{text('取消', 'Cancel')}</button><button className="button primary" disabled={saving}>{saving ? text('创建中…', 'Creating…') : text('创建项目', 'Create project')}</button></div></form></Modal>;
}
