import { useState, type FormEvent } from 'react';
import type { Project, Status, Task, TaskInput, TaskPatch } from '../../../../packages/contracts/index.ts';
import { priorities, priorityLabels, statuses, statusLabels } from '../../../../packages/contracts/index.ts';
import { Modal, ErrorMessage } from './shared';

export function TaskModal({ project, task, initialStatus = 'todo', onClose, onSubmit, pending }: { project: Project; task?: Task; initialStatus?: Status; onClose: () => void; onSubmit: (input: TaskInput | Partial<TaskPatch>) => void; pending: boolean }) {
  const [title, setTitle] = useState(task?.title ?? ''); const [description, setDescription] = useState(task?.description ?? ''); const [status, setStatus] = useState<Status>(task?.status ?? initialStatus); const [priority, setPriority] = useState<Task['priority']>(task?.priority ?? 'none'); const [assignee, setAssignee] = useState(task?.assignee ?? ''); const [startDate, setStartDate] = useState(task?.startDate ?? ''); const [dueDate, setDueDate] = useState(task?.dueDate ?? ''); const [labels, setLabels] = useState(task?.labels.join(', ') ?? ''); const [error, setError] = useState<string | null>(null);
  function submit(event: FormEvent) { event.preventDefault(); if (!title.trim()) { setError('请输入任务标题'); return; } if (startDate && dueDate && startDate > dueDate) { setError('开始日期不能晚于截止日期'); return; } const base = { title: title.trim(), description, status, priority, assignee, startDate: startDate || null, dueDate: dueDate || null, labels: labels.split(',').map((value) => value.trim()).filter(Boolean) }; if (task) onSubmit(base); else onSubmit({ ...base, projectId: project.id }); }
  return <Modal title={task ? `编辑 ${task.identifier}` : `在 ${project.name} 中新建任务`} onClose={onClose} wide><form className="task-form" onSubmit={submit}><div className="task-form-main"><label>标题<input autoFocus value={title} onChange={(event) => setTitle(event.target.value)} placeholder="要完成什么？" /></label><label>描述<span className="field-hint">支持 Markdown</span><textarea value={description} onChange={(event) => setDescription(event.target.value)} placeholder="补充背景、验收标准或相关链接" rows={9} /></label></div><div className="task-form-side"><label>状态<select value={status} onChange={(event) => setStatus(event.target.value as Status)}>{statuses.map((item) => <option key={item} value={item}>{statusLabels[item]}</option>)}</select></label><label>优先级<select value={priority} onChange={(event) => setPriority(event.target.value as Task['priority'])}>{priorities.map((item) => <option key={item} value={item}>{priorityLabels[item]}</option>)}</select></label><label>负责人<input value={assignee} onChange={(event) => setAssignee(event.target.value)} placeholder="用户名或 Agent" /></label><label>标签<span className="field-hint">使用逗号分隔</span><input value={labels} onChange={(event) => setLabels(event.target.value)} placeholder="frontend, mvp" /></label><div className="date-grid"><label>开始日期<input type="date" value={startDate} onChange={(event) => setStartDate(event.target.value)} /></label><label>截止日期<input type="date" value={dueDate} onChange={(event) => setDueDate(event.target.value)} /></label></div></div><ErrorMessage error={error} /><div className="form-actions"><button type="button" className="button secondary" onClick={onClose}>取消</button><button className="button primary" disabled={pending}>{pending ? '保存中…' : task ? '保存修改' : '创建任务'}</button></div></form></Modal>;
}
